### ISSUE TITLE
When will TiKV-python-client release?

### ISSUE THREAD

**Issue by DonYum** [tikv/client-py#15]
TiKV is amazing! 
We decide to adopt TiKV in our project, however, it's python client is not released.
So, can anyone tell me, what's your plan? and when will TiKV-python-client release?

BRs!

**Comment by andylokandy** [comment]
We don't have a clear plan for the python client yet. You can use rust client. java client or go client if you're supposed to use TiKV in a short time. 

However, you are welcome to contribute to the python client so as to move it to a release stage. I can give you a roadmap and detailed guide if you'd like to.

**Comment by andylokandy** [comment]
@DonYum python client has been published: https://pypi.org/project/tikv-client/
