### ISSUE TITLE
Release cycle ?

### ISSUE THREAD

**Issue by bloodbare** [tikv/client-py#24]
I would like to ask how the release cycle of this project is managed. @andylokandy

**Comment by andylokandy** [comment]
@bloodbare We don't have a concrete release plan for client-py yet. Anyway, in common situations, we'll release a new version right after a PR get merged. But now the window build on CI is still failing and I haven't come to a good way to solve it.

**Comment by bloodbare** [comment]
I see, sorry I don't have a lot of windows experience to help. I'll try to check it also.

**Comment by andylokandy** [comment]
Released 0.0.3, going to close this issue.
