### ISSUE TITLE
return list or tuple in client.scan method?

### ISSUE THREAD

**Issue by cosven** [tikv/client-py#3]
Currently, the `RawClient.scan` return a dict:
https://github.com/tikv/client-py/blob/27d14d7e413726712e68a2ba28a3fd5cf1ab45f2/src/raw.rs#L77-L78

However, the dict may be unordered(depending on Python interpreter implementation). As a result, it's hard for us to get the biggest key from the scan response. I want to use the biggest key as the start key of the next scan request.

**Comment by andylokandy** [comment]
This may work for you:

```python
>>> kvpairs = {"k1": "v1", "k2": "v2"}
>>> max(kvpairs)
'k2'
```

**Comment by cosven** [comment]
> This may work for you:
> 
> ```python
> >>> kvpairs = {"k1": "v1", "k2": "v2"}
> >>> max(kvpairs)
> 'k2'
> ```

Yeah, it works, but it brings some unneccesary overhead.

To my understanding, tikv return sorted kv pairs. The client SHOULD just directly return the sorted paris.
User can conver kv pairs to dict in application level.

**Comment by andylokandy** [comment]
Good point

**Comment by andylokandy** [comment]
But IMO, returning tuples or objects brings more overhead because you'll always convert it into a dict in most scenario.
