### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by vangheem** [tikv/client-py#34]
Would it be possible to get a new pypi release?

**Comment by lferran** [comment]
@andylokandy ?

**Comment by andylokandy** [comment]
A successful CI build on master branch will publish a new release to PyPI. Seems that the latest build is failed for some reasons.

**Comment by andylokandy** [comment]
Since PyPI banned old upload api this week ([link](https://discuss.python.org/t/announcement-2fa-now-required-for-pypi/42251)), I'm waiting for the build tool update ([link](https://github.com/pypa/twine/issues/561)).

**Comment by woodruffw** [comment]
FYIm You don't need a build tool update here: existing releases of `twine` support API tokens.

If you have an API token provisioned, you can set `username = __token__` (the literal string `__token__`) and `password = pypi-...`, where `pypi-...` is the API token value.

**Comment by andylokandy** [comment]
released v0.0.4
