### ISSUE TITLE
TransactionClient can't connect to pd address

### ISSUE THREAD

**Issue by huangaijian** [tikv/client-py#5]
from tikv_client import TransactionClient
>>> client = TransactionClient.connect("127.0.0.1:2379")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'TransactionClient' has no attribute 'connect'

**Comment by andylokandy** [comment]
Oh, seems that the new version is not published automatically. I'll fix it.

**Comment by andylokandy** [comment]
It should be fixed. Try `pip3 install -i https://test.pypi.org/simple/ tikv-client --upgrade`.

**Comment by huangaijian** [comment]
thx, it seems ok now
